---
title: "Практическая работа №7"
author: "koltsivers@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1.  Изучить возможности технологии Yandex Query для анализа структурированных наборов данных
2.  Получить навыки построения аналитического пайплайна для анализа данных с помощью сервисов Yandex Cloud
3.  Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети

## Исходные данные

1.  Программное обеспечение ОС Windows 11 Pro
2.  RStudio
3.  Интерпретатор языка R 4.5.1

## План

1.  Используя сервис Yandex Query настроить доступ к данным, хранящимся
    в сервисе хранения данных Yandex Object Storage.
2.  Проверьте доступность данных (файл yaqry_dataset.pqt) в бакете
    arrow-datasets S3 хранилища Yandex Object Storage.
3.  Известно, что IP адреса внутренней сети начинаются с октетов,
    принадлежащих интервалу \[12-14\]. Определите количество хостов
    внутренней сети, представленных в датасете.
4.  Определите суммарный объем исходящего трафика.
5.  Определите суммарный объем входящего трафика.

## Шаги:

### Загрузка библиотек
