---
title: "Практическая работа №4"
author: "koltsivers@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1. Закрепить практические навыки использования языка программирования R для обработки данных
2. Закрепить знания основных функций обработки данных экосистемы tidyverse языка R
3. Закрепить навыки исследования метаданных DNS трафика

## Исходные данные

1. Программное обеспечение Microsoft Windows 11 Pro
2. RStudio Desktop
3. Интерпретатор языка R 4.5.2

## Задание

Используя программный пакет dplyr, освоить анализ DNS логов с помощью языка программирования R.

## Ход работы

1. Импортируйте данные DNS – https://storage.yandexcloud.net/dataset.ctfsec/dns.zip. Данные были собраны с помощью сетевого анализатора zeek
2. Добавьте пропущенные данные о структуре данных (назначении столбцов)
3. Преобразуйте данные в столбцах в нужный формат,просмотрите общую структуру данных с помощью функции glimpse()
4. Сколько участников информационного обмена всети Доброй Организации?
5. Какое соотношение участников обмена внутрисети и участников обращений к внешним ресурсам?
6. Найдите топ-10 участников сети, проявляющих наибольшую сетевую активность.
7. Найдите топ-10 доменов, к которым обращаются пользователи сети и соответственное количество обращений
8. Определите базовые статистические характеристики (функция summary() ) интервала времени между последовательными обращениями к топ-10 доменам.
9. Часто вредоносное программное обеспечение использует DNS канал в качестве канала управления, периодически отправляя запросы на подконтрольный злоумышленникам DNS сервер. По периодическим запросам на один и тот же домен можно выявить скрытый DNS канал. Есть ли такие IP адреса в исследуемом датасете?
10. Определите местоположение (страну, город) и организацию-провайдера для топ-10 доменов. Для этого можно использовать сторонние сервисы,например http://ip-api.com (API-эндпоинт –
http://ip-api.com/json).
11. Оценить результаты и сделать вывод

## Шаги:

### Шаг 1: Импортируйте данные DNS – https://storage.yandexcloud.net/dataset.ctfsec/dns.zip. Данные были собраны с помощью сетевого анализатора zeek



### Шаг 2: Добавьте пропущенные данные о структуре данных (назначении столбцов)



### Шаг 3: Преобразуйте данные в столбцах в нужный формат,просмотрите общую структуру данных с помощью функции glimpse()



### Шаг 4: Сколько участников информационного обмена всети Доброй Организации?



### Шаг 5: Какое соотношение участников обмена внутрисети и участников обращений к внешним ресурсам?



### Шаг 6: Найдите топ-10 участников сети, проявляющих наибольшую сетевую активность.



### Шаг 7: Найдите топ-10 доменов, к которым обращаются пользователи сети и соответственное количество обращений



### Шаг 8: Определите базовые статистические характеристики (функция summary() ) интервала времени между последовательными обращениями к топ-10 доменам.



### Шаг 9: Часто вредоносное программное обеспечение использует DNS канал в качестве канала управления, периодически отправляя запросы на подконтрольный злоумышленникам DNS сервер. По периодическим запросам на один и тот же домен можно выявить скрытый DNS канал. Есть ли такие IP адреса в исследуемом датасете?



### Шаг 10: Определите местоположение (страну, город) и организацию-провайдера для топ-10 доменов. Для этого можно использовать сторонние сервисы,например http://ip-api.com (API-эндпоинт – http://ip-api.com/json).



### Шаг 11: Оценить результаты и сделать вывод


